security:
  jwt:
    token:
      secret-key: 57cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/favorite-products
    username: postgres
    password: luizalabs-interview
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false